---
netbox_project_dir: /opt/netbox
netbox_image: netboxcommunity/netbox:v4.5.10-4.0.2
netbox_postgres_image: postgres:18-alpine
netbox_valkey_image: valkey/valkey:9.0-alpine
netbox_bind_address: 127.0.0.1
netbox_http_port: 8000
netbox_allowed_hosts:
  - localhost

netbox_database_name: netbox
netbox_database_user: netbox
netbox_secret_key: "<NETBOX_SECRET_KEY>"
netbox_postgres_password: "<POSTGRES_PASSWORD>"
netbox_redis_password: "<REDIS_PASSWORD>"
netbox_redis_cache_password: "<REDIS_CACHE_PASSWORD>"
netbox_superuser_name: admin
netbox_superuser_email: "<ADMIN_EMAIL>"
netbox_superuser_password: "<NETBOX_ADMIN_PASSWORD>"

netbox_enable_metrics: true
netbox_enable_traefik: false
netbox_traefik_hostname: "netbox.<BASE_DOMAIN>"
netbox_traefik_network: proxy
netbox_manage_firewall: false
netbox_validation_host: 127.0.0.1
