FROM {{ netbox_image }}

COPY plugin-requirements.txt /opt/netbox/plugin-requirements.txt
COPY plugins.py /etc/netbox/config/plugins.py
{% if netbox_topology_views_enabled | bool %}
COPY topology-role-unknown.svg /opt/netbox/netbox/static/netbox_topology_views/img/role-unknown.svg
{% endif %}
RUN /usr/local/bin/uv pip install --no-cache --requirement /opt/netbox/plugin-requirements.txt \
{% if netbox_topology_views_enabled | bool %}
    && mkdir -p /opt/netbox/netbox/static/netbox_topology_views/img \
{% endif %}
    && rm -f /opt/netbox/plugin-requirements.txt
