---
portainer_project_dir: /opt/portainer
portainer_image: portainer/portainer-ce:2.39.5-alpine
portainer_admin_user: admin
portainer_admin_password: "<PORTAINER_ADMIN_PASSWORD>"

portainer_bind_address: 127.0.0.1
portainer_http_port: 9000
portainer_validation_host: 127.0.0.1

portainer_enable_traefik: false
portainer_traefik_hostname: "portainer.<BASE_DOMAIN>"
portainer_traefik_additional_hostnames: []
portainer_traefik_network: proxy
portainer_traefik_middlewares:
  - security-headers@file
portainer_traefik_validation_address: 127.0.0.1
portainer_traefik_https_port: 443
