---
docker_repository_url: https://download.docker.com/linux/rhel/docker-ce.repo
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
docker_compose_package: docker-compose-plugin-2.40.3-1.el9
docker_users: []
docker_daemon_config:
  log-driver: json-file
  log-opts:
    max-size: 10m
    max-file: "3"
  live-restore: true
